# ===============================
# Chestsort+ Plugin Configuration
# ===============================

config:
  # current plugin version, do not change this
  version: ${version}

button:
  # item shown in the player's hotbar while viewing a sortable container
  material: HOPPER
  name: "&a&lSort Chest"
  # hotbar slot (0-8), default 8 is the rightmost hotbar slot
  slot: 8

categories:
  - combat
  - tools_and_utilities
  - food_and_drinks
  - ingredients
  - spawn_eggs
  - building_blocks
  - colored_blocks
  - natural_blocks
  - functional_blocks
  - redstone_blocks
  - op_blocks
